- third-file
> Homework 2

- leyla/src/src/ConditionalStatements.java
- leyla/src/src/Main.java
- leyla/src/src/PalindromeChecker.java
- leyla/src/src/Prime.java
> Leyla Session 5

- turqut/src/Lesson5task1.java
- turqut/src/Lesson5task2.java
- turqut/src/Lesson5task3.java
You can see my solutions for homework
> This is my homework3

- turqut/src/ArraysSession7.java
I solved 30 problems in the given link for homework.
> ArraysSession7

- javad/src/Session5/Hw1.java
- javad/src/Session5/Hw2.java
- javad/src/Session5/W3School/task1.java
- javad/src/Session5/W3School/task10.java
- javad/src/Session5/W3School/task11.java
- javad/src/Session5/W3School/task12.java
- javad/src/Session5/W3School/task13.java
- javad/src/Session5/W3School/task14.java
- javad/src/Session5/W3School/task15.java
- javad/src/Session5/W3School/task16.java
- javad/src/Session5/W3School/task17.java
- javad/src/Session5/W3School/task18.java
- javad/src/Session5/W3School/task19.java
- javad/src/Session5/W3School/task2.java
- javad/src/Session5/W3School/task20.java
- javad/src/Session5/W3School/task3.java
- javad/src/Session5/W3School/task4.java
- javad/src/Session5/W3School/task5.java
- javad/src/Session5/W3School/task6.java
- javad/src/Session5/W3School/task7.java
- javad/src/Session5/W3School/task8.java
- javad/src/Session5/W3School/task9.java
Session5 homeworks and W3School tasks
> javadSession5

- turqut/src/TurqutMethodsClassWork1AsHomeWork.java
- turqut/src/TurqutMethodsHomeWork1.java
- turqut/src/TurqutMethodsHomeWork2Arrays.java
- turqut/src/TurqutMethodsHomeWork2Math.java
- turqut/src/TurqutMethodsHomeWork2String.java
I solve for all homework with details.
> Methods Homeworks

- turqut/src/TurqutMethodsClassWork1AsHomeWork.java
- turqut/src/TurqutMethodsHomeWork1.java
- turqut/src/TurqutMethodsHomeWork2Arrays.java
- turqut/src/TurqutMethodsHomeWork2Math.java
- turqut/src/TurqutMethodsHomeWork2String.java
- turqut/src/TurqutTestingHomeWork1.java
- turqut/src/TurqutTestingHomeWork2.java
- turqut/src/TurqutTestingHomeWork3Arrays.java
- turqut/src/TurqutTestingHomeWork3Math.java
- turqut/src/TurqutTestingHomeWork3String.java
I modified methods in session8 homework, change from private to public for testing. And also I write for testing, testing methods with @Test annotation for all session8 methods.
> Session9-Testing homework

- aysel/src/Main.java
- aysel/src/Session11/Book.java
- aysel/src/Session11/BookCollection.java
- aysel/src/Session11/Circle.java
- aysel/src/Session11/Dog.java
- aysel/src/Session11/Employee.java
- aysel/src/Session11/Person.java
- aysel/src/Session11/Rectangle.java
- aysel/src/Session11/TrafficLight.java
> HomeWork-Session-11

- leyla/src/array.java
> Leyla-Session-7

- leyla/src/MethodHomeWork1.java
- leyla/src/Session8.java
- leyla/src/array.java
> Leyla session8

- shammad/src/session12CourseworkForHome/todoLesson/Entity/Task.java
- shammad/src/session12CourseworkForHome/todoLesson/MainApp.java
- shammad/src/session12CourseworkForHome/todoLesson/enums/TaskStatus.java
- shammad/src/session12CourseworkForHome/todoLesson/service/ITaskManager.java
- shammad/src/session12CourseworkForHome/todoLesson/service/impl/TaskManager.java
-Removed findAll() method due to its redundancy.
+Added exception handlings
> coursework modified and optimized handling of exceptions

- turqut/Mobile Games Library first-app/src/App.java
- turqut/Mobile Games Library first-app/src/model/Game.java
- turqut/Mobile Games Library first-app/src/model/GameCategory.java
- turqut/Mobile Games Library first-app/src/service/GameLibrary.java
- turqut/Mobile Games Library first-app/src/service/impl/MobileGamesLibraryImpl.java
> Mobile Games Library

- shammad/src/session12CourseworkForHome/test/TaskManagerTest.java
- shammad/src/session12CourseworkForHome/todoLesson/enums/TaskStatus.java
- shammad/src/session12CourseworkForHome/todoLesson/service/impl/TaskManager.java
+Added exception throw type to the TaskStatus method
+Handled exception occuring from TaskStatus
+Added tests for TaskManager methods
Kept previous code by commenting [to see the progress]
> Shammad session13 exceptions and tests

- saleh/src/session4/Homework4.java
- saleh/src/session4/SessionTest.java
- saleh/src/session8/HomeWork1.java
- saleh/src/session9/MethodsPracticeTest.java
- saleh/src/session9/Practice.java
> Saleh session home work8 1

- shammad/src/productsHomework/Main.java
- shammad/src/productsHomework/entity/Product.java
- shammad/src/productsHomework/entity/ProductCategory.java
- shammad/src/productsHomework/entity/ProductType.java
- shammad/src/productsHomework/enums/Status.java
- shammad/src/productsHomework/exceptions/CapacityIsFullException.java
- shammad/src/productsHomework/exceptions/CategoryDoesNotMatchException.java
- shammad/src/productsHomework/exceptions/InactiveProductTypeException.java
- shammad/src/productsHomework/repository/ProductRepository.java
- shammad/src/productsHomework/service/ProductService.java
Tried to use all lessons we have been taught.
Removing product scenario is not considered.
(note: ctrl+alt+L is done.)
> Products project by Shammad

- aysel/src/Session6/HomeWork3.java
- aysel/src/Session6/HomeWorkChanges.java
> Aysel-Session-7

- turqut/src/productApp/App.java
- turqut/src/productApp/model/Product.java
- turqut/src/productApp/model/ProductCategory.java
- turqut/src/productApp/model/ProductType.java
- turqut/src/productApp/model/Status.java
- turqut/src/productApp/service/ProductManagement.java
- turqut/src/productApp/service/impl/ProductManagementImpl.java
> Product App

- turqut/src/searchingAndSorting/searchingAndSorting.java
> Searching and sorting algorithms

- turqut/src/collections/Task1
- turqut/src/collections/Task2.java
> Data Structure Homework

- turqut/src/collections/Task3.java
- turqut/src/collections/dataStructure2ClassExercise/Grade.java
- turqut/src/collections/dataStructure2ClassExercise/MainWithMap.java
- turqut/src/collections/dataStructure2ClassExercise/MainWithStream.java
- turqut/src/collections/dataStructure2ClassExercise/Student.java
Finally, I do all homeworks about collections
> All homeworks about collections

- aysel/src/Session17/LeetCodeHW.java
- aysel/src/Session17/Main.java
> LeetCode HomeWork

- leyla/src/Session13/Exceptions.java
- leyla/src/Session13/Impl/TodoServiceImpl.java
- leyla/src/Session13/Model/Todo.java
- leyla/src/Session13/Model/TodoStatus.java
- leyla/src/Session13/Service/TodoService.java
- leyla/src/Session20/StreamTasks.java
> Leyla session20

- leyla/src/Session13/Exceptions.java
- leyla/src/Session13/Impl/TodoServiceImpl.java
- leyla/src/Session13/Model/Todo.java
- leyla/src/Session13/Model/TodoStatus.java
- leyla/src/Session13/Service/TodoService.java
> LeylaSession13

- turqut/src/collections/dataStructure2ClassExercise/MainWithFileIO.java
- turqut/src/collections/dataStructure2ClassExercise/Student.java
I solve homework. When lecturer update task, I will update solvings.
> File Management Homework

- turqut/src/streams/ClassWork.java
> Streams classwork

- elshan/src/Algorithms/SearchingAlgorithms.java
- elshan/src/Algorithms/SortingAlgorithms.java
This file provides Java implementations of Searching and Sorting algorithms
1. Searching algoritms : 
2. Sorting algorithms :
> Algorithms

- javad/src/Session14/ProductApp/Main.java
- javad/src/Session14/ProductApp/Product.java
- javad/src/Session14/ProductApp/ProductCategory.java
- javad/src/Session14/ProductApp/ProductManager.java
- javad/src/Session14/ProductApp/ProductManagerImpl.java
- javad/src/Session14/ProductApp/ProductType.java
> Javad Session14 

- turqut/src/module1Tasks/NumberGuess.java
- turqut/src/module1Tasks/ShipBattle.java
- turqut/src/module1Tasks/WeekPlanner.java
> Module1 Tasks
